First release
pagopa/subdomain-takeover-monitoring pull request #1
Opened 2024-07-15 15:47 UTC by FilippoBau

2024-09-02 14:56 UTC, himazawa requested changes
Need improvements

2024-09-06 07:26 UTC, FilippoBau commented on cmd/aws/aws.go
> +	fmt.Println("event", event)
The script for the aws part has not been implemented yet, this is the default script

2024-09-06 07:26 UTC, FilippoBau commented on cmd/aws/aws.go
> +	return "Hello world", nil
The script for the aws part has not been implemented yet, this is the default script

2024-09-23 13:01 UTC, himazawa requested changes

2024-09-23 13:01 UTC, himazawa commented on cmd/azure/azure_test.go
> +				return
This is blocking the execution of other tests, why?

2024-09-24 08:59 UTC, FilippoBau commented on .gitignore
> +cmd/parsing/
These are routes used for temporary activities or debugging purposes. They are in gitignore to avoid unintended push.

2024-10-28 15:17 UTC, himazawa approved these changes

2024-10-28 15:17 UTC, merged